<?php

namespace Database\Seeders;

use App\Models\Location\Country;
use App\Models\Location\State;
use App\Models\Location\Town;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TownSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
            [
                'code' => 'FC',
                'name' => 'Abuja',
                'lgas' => ['Abuja', 'Kwali', 'Kuje', 'Gwagwalada', 'Bwari', 'Abaji'],
                'cities' => [
                    'Bamburu',
                    'Mararaba',
                    'Gwarinpa',
                    'Abuja',
                    'Gwagwalada',
                    'Wuse',
                    'Maitama',
                    'Garki',
                    'Asokoro',
                    'Karu',
                    'Kubwa',
                    'Kurunduma ',
                    'Jikwoyi',
                    'Masaka',
                    'New Nyanya',
                    'Karshi',
                    'Yoba',
                    'Zuba',
                ],
            ],
            [
                'code' => 'AB',
                'name' => 'Abia',
                'lgas' => [
                    'Aba North',
                    'Aba South',
                    'Arochukwu',
                    'Bende',
                    'Ikawuno',
                    'Ikwuano',
                    'Isiala-Ngwa North',
                    'Isiala-Ngwa South',
                    'Isuikwuato',
                    'Umu Nneochi',
                    'Obi Ngwa',
                    'Obioma Ngwa',
                    'Ohafia',
                    'Ohaozara',
                    'Osisioma',
                    'Ugwunagbo',
                    'Ukwa West',
                    'Ukwa East',
                    'Umuahia North',
                    'Umuahia South',
                ],
                'cities' => [
                    'Aba',
                    'Umuahia',
                    'Osisioma',
                    'Mgboko',
                    'Okpuala-Ngwa',
                    'Isiala Oboro',
                    'Omoba',
                    'Arochukwu',
                    'Bende',
                    'Ebem Ohafia',
                    'Nkwoagu Isuochi',
                    'Mbalano',
                    'Oke-Ikpe',
                    'Akwete',
                ],
            ],
            [
                'code' => 'AD',
                'name' => 'Adamawa',
                'lgas' => [
                    'Demsa',
                    'Fufore',
                    'Ganye',
                    'Girei',
                    'Gombi',
                    'Guyuk',
                    'Hong',
                    'Jada',
                    'Lamurde',
                    'Madagali',
                    'Maiha',
                    'Mayo-Belwa',
                    'Michika',
                    'Mubi-North',
                    'Mubi-South',
                    'Numan',
                    'Shelleng',
                    'Song',
                    'Toungo',
                    'Yola North',
                    'Yola South',
                ],
                'cities' => [
                    'Yola',
                    'Mubi',
                    'Numan',
                    'Shelleng',
                    'Gulak',
                    'Michika',
                    'Gella',
                    'Maiha',
                    'Fufore',
                    'Girei',
                    'Guyuk',
                    'Lamurde',
                    'Ganye',
                    'Demsa',
                    'Jimeta',
                    'Jada',
                    'Mayo-Belwa',
                    'Gombi',
                    'Hong',
                    'Song',
                    'Toungo',
                ],
            ],
            [
                'code' => 'AK',
                'name' => 'AkwaIbom',
                'lgas' => [
                    'Abak',
                    'Eastern-Obolo',
                    'Eket',
                    'Esit-Eket',
                    'Essien-Udim',
                    'Etim-Ekpo',
                    'Etinan',
                    'Ibeno',
                    'Ibesikpo-Asutan',
                    'Ibiono-Ibom',
                    'Ika',
                    'Ikono',
                    'Ikot-Abasi',
                    'Ikot-Ekpene',
                    'Ini',
                    'Itu',
                    'Mbo',
                    'Mkpat-Enin',
                    'Nsit-Atai',
                    'Nsit-Ibom',
                    'Nsit-Ubium',
                    'Obot-Akara',
                    'Okobo',
                    'Onna',
                    'Oron',
                    'Oruk Anam',
                    'Udung-Uko',
                    'Ukanafun',
                    'Urue-Offong/Oruko',
                    'Uruan',
                    'Uyo',
                ],
                'cities' => [
                    'Abak',
                    'Afaha',
                    'Anakpa',
                    'Asanga',
                    'Eastern-Obolo',
                    'Eket',
                    'Ekpene-Ukim',
                    'Esit-Eket',
                    'Essien-Udim',
                    'Etim-Ekpo',
                    'Etinan',
                    'Eyofin',
                    'Ibeno',
                    'Ibesikpo-Asutan',
                    'Ibiono-Ibom',
                    'Idu',
                    'Ika',
                    'Ikono',
                    'Ikot-Abasi',
                    'Ikot-Afang',
                    'Ikot-Ekpene',
                    'Ikot-Ibritan',
                    'Ikot-Ido Abia',
                    'Ikot-Okoro',
                    'Ikot-Onwon',
                    'Ini',
                    'Itu',
                    'Mbo',
                    'Mkpat-Enin',
                    'Nsit-Atai',
                    'Nsit-Ibom',
                    'Nsit-Ubium',
                    'Ntak-Ibesit',
                    'Obio-Ndobo',
                    'Obolo',
                    'Obot-Akara',
                    'Okobo',
                    'Onna',
                    'Oron',
                    'Oruk Anam',
                    'Otung',
                    'Oyubia',
                    'Oyuko-Ibighi',
                    'Ubodung',
                    'Udung-Uko',
                    'Ukanafun',
                    'Urue-Offong/Oruko',
                    'Uruan',
                    'Usuk Obi Ediene',
                    'Uyo',
                ],
            ],
            [
                'code' => 'AN',
                'name' => 'Anambra',
                'lgas' => [
                    'Aguata',
                    'Anambra East',
                    'Anambra West',
                    'Anaocha',
                    'Awka North',
                    'Awka South',
                    'Ayamelum',
                    'Dunukofia',
                    'Ekwusigo',
                    'Idemili-North',
                    'Idemili-South',
                    'Ihiala',
                    'Njikoka',
                    'Nnewi-North',
                    'Nnewi-South',
                    'Ogbaru',
                    'Onitsha-North',
                    'Onitsha-South',
                    'Orumba-North',
                    'Orumba-South',
                ],
                'cities' => [
                    'Abagana',
                    'Abba',
                    'Adazi Ani',
                    'Adazi Enu',
                    'Adazi Nnukwu',
                    'Aguleri',
                    'Agulu',
                    'Alor',
                    'Amaokpala',
                    'Amawbia',
                    'Atani',
                    'Awgbu',
                    'Awka',
                    'Awka-Etiti',
                    'Awkuzu',
                    'Ekwulobia',
                    'Enugwu-Agidi',
                    'Enugwu-Ukwu',
                    'Ichida',
                    'Igbo-Ukwu',
                    'Ihiala',
                    'Isuofia',
                    'Nanka',
                    'Nawfia',
                    'Nawgu',
                    'Neni',
                    'Nibo',
                    'Nkpor',
                    'Nnewi',
                    'Nnobi',
                    'Oba',
                    'Obosi',
                    'Ogidi',
                    'Okija',
                    'Oko',
                    'Onitsha',
                    'Oraifite',
                    'Otuocha',
                    'Oyi',
                    'Ozubulu',
                    'Ukpo',
                    'Umuchu',
                    'Umudioka',
                    'Umuleri',
                    'Umunnachi',
                    'Umunya',
                    'Unubi',
                ],
            ],
            [
                'code' => 'BA',
                'name' => 'Bauchi',
                'lgas' => [
                    'Alkaleri',
                    'Bauchi',
                    'Bogoro',
                    'Damban',
                    'Darazo',
                    'Dass',
                    'Gamawa',
                    'Ganjuwa',
                    'Giade',
                    'Itas Gadau',
                    "Jama'Are",
                    'Katagum',
                    'Kirfi',
                    'Misau',
                    'Ningi',
                    'Shira',
                    'Tafawa-Balewa',
                    'Toro',
                    'Warji',
                    'Zaki',
                ],
                'cities' => [
                    'Bauchi',
                    'Azare',
                    'Yana',
                    'Giade',
                    'Jama’are',
                    'Misau',
                    'Warji',
                    'Dass',
                    'Dambam',
                    'Itas',
                    'Bogoro',
                    'Katagum',
                    'Tafawa Balewa',
                    'Darazo',
                    'Gamawa',
                    'Ningi',
                    'Kirfi',
                    'Alkaleri',
                    'Kafin Madaki',
                    'Toro',
                ],
            ],
            [
                'code' => 'BY',
                'name' => 'Bayelsa',
                'lgas' => [
                    'Brass',
                    'Ekeremor',
                    'Kolokuma Opokuma',
                    'Nembe',
                    'Ogbia',
                    'Sagbama',
                    'Southern-Ijaw',
                    'Yenagoa',
                ],
                'cities' => [
                    'Yenagoa',
                    'Ogbia',
                    'Sagbama',
                    'Kaiama',
                    'Nembe',
                    'Ekeremor',
                    'Oporoma',
                    'Twon-Brass',
                ],
            ],
            [
                'code' => 'BE',
                'name' => 'Benue',
                'lgas' => [
                    'Ado',
                    'Agatu',
                    'Apa',
                    'Buruku',
                    'Gboko',
                    'Guma',
                    'Gwer-East',
                    'Gwer-West',
                    'Katsina-Ala',
                    'Konshisha',
                    'Kwande',
                    'Logo',
                    'Makurdi',
                    'Ogbadibo',
                    'Ohimini',
                    'Oju',
                    'Okpokwu',
                    'Otukpo',
                    'Tarka',
                    'Ukum',
                    'Ushongo',
                    'Vandeikya',
                ],
                'cities' => [
                    'Makurdi',
                    'Otukpo',
                    'Vandeikya',
                    'Okpoga',
                    'Obarike-Ito',
                    'Wannune',
                    'Otukpa',
                    'Gboko',
                    'Igumale',
                    'Oju',
                    'Lessel',
                    'Adikpo',
                    'Tse-Agberagba',
                    'Sankera',
                    'Buruku',
                    'Ugba',
                    'Ugbokpo',
                    'Naka',
                    'Obagaji',
                    'Katsina-Ala',
                    'Gbajimba',
                    'Aliade',
                ],
            ],
            [
                'code' => 'BO',
                'name' => 'Borno',
                'lgas' => [
                    'Abadam',
                    'Askira-Uba',
                    'Bama',
                    'Bayo',
                    'Biu',
                    'Chibok',
                    'Damboa',
                    'Dikwa',
                    'Gubio',
                    'Guzamala',
                    'Gwoza',
                    'Hawul',
                    'Jere',
                    'Kaga',
                    'Kala Balge',
                    'Konduga',
                    'Kukawa',
                    'Kwaya-Kusar',
                    'Mafa',
                    'Magumeri',
                    'Maiduguri',
                    'Marte',
                    'Mobbar',
                    'Monguno',
                    'Ngala',
                    'Nganzai',
                    'Shani',
                ],
                'cities' => [
                    'Maiduguri',
                    'Bama',
                    'Biu',
                    'Khaddamari',
                    'Gamboru',
                    'Briyel',
                    'Gwoza',
                    'Shani',
                    'Kwaya Kusar',
                    'Askira',
                    'Gubio',
                    'Azare',
                    'Dikwa',
                    'Rann',
                    'Chibok',
                    'Kukawa',
                    'Marte',
                    'Gudumbali',
                    'Monguno',
                    'Gajiram',
                    'Damboa',
                    'Damasak',
                    'Mafa',
                    'Benisheikh',
                    'Magumeri',
                    'Konduga',
                    'Mallam Fatori',
                ],
            ],
            [
                'code' => 'CR',
                'name' => 'CrossRiver',
                'lgas' => [
                    'Abi',
                    'Akamkpa',
                    'Akpabuyo',
                    'Bakassi',
                    'Bekwarra',
                    'Biase',
                    'Boki',
                    'Calabar-Municipal',
                    'Calabar-South',
                    'Etung',
                    'Ikom',
                    'Obanliku',
                    'Obubra',
                    'Obudu',
                    'Odukpani',
                    'Ogoja',
                    'Yakurr',
                    'Yala',
                ],
                'cities' => [
                    'Ababene',
                    'Adadama',
                    'Akamkpa',
                    'Akpabuyo',
                    'Bekwarra',
                    'Boki',
                    'Calabar',
                    'Calabar-South',
                    'Biase',
                    'Odukpani',
                    'Ogoja',
                    'Obudu',
                    'Ikom',
                    'Obubra',
                    'Obanliku',
                    'Ugep',
                    'Usumutong',
                    'Inyima',
                    'Idomi',
                    'Okuku',
                    'Afafanyi',
                    'Akpap',
                    'Etung',
                    'Epenti',
                    'Ediba',
                    'Agarabe',
                ],
            ],
            [
                'code' => 'DE',
                'name' => 'Delta',
                'lgas' => [
                    'Aniocha North',
                    'Aniocha-North',
                    'Aniocha-South',
                    'Bomadi',
                    'Burutu',
                    'Ethiope-East',
                    'Ethiope-West',
                    'Ika-North-East',
                    'Ika-South',
                    'Isoko-North',
                    'Isoko-South',
                    'Ndokwa-East',
                    'Ndokwa-West',
                    'Okpe',
                    'Oshimili-North',
                    'Oshimili-South',
                    'Patani',
                    'Sapele',
                    'Udu',
                    'Ughelli-North',
                    'Ughelli-South',
                    'Ukwuani',
                    'Uvwie',
                    'Warri South-West',
                    'Warri North',
                    'Warri South',
                ],
                'cities' => [
                    'Warri',
                    'Sapele',
                    'Burutu',
                    'Effurun',
                    'Asaba',
                    'Otor-Udu',
                    'Otu-Jeremi',
                    'Bomadi',
                    'Isiokolo',
                    'Ughelli',
                    'Oghara',
                    'Owa-Oyibu',
                    'Oleh',
                    'Patani',
                    'Agbor',
                    'Ozoro',
                    'Orerokpe',
                    'Obiaruku',
                    'Akwukwu-Igbo',
                    'Issele-Uku',
                    'Kwale',
                    'Ogwashi-Uku',
                    'Koko',
                    'Ogbe-Ijoh',
                    'Aboh',
                ],
            ],
            [
                'code' => 'EB',
                'name' => 'Ebonyi',
                'lgas' => [
                    'Abakaliki',
                    'Afikpo-North',
                    'Afikpo South (Edda)',
                    'Ebonyi',
                    'Ezza-North',
                    'Ezza-South',
                    'Ikwo',
                    'Ishielu',
                    'Ivo',
                    'Izzi',
                    'Ohaukwu',
                    'Onicha',
                ],
                'cities' => [
                    'Abakaliki',
                    'Afikpo',
                    'Isu',
                    'Obiozara',
                    'Nguzu Edda',
                    'Onuebonyi Echara',
                    'Isiaka',
                    'Onueke',
                    'Ezzamgbo',
                    'Ugbodo',
                    'Iboko',
                    'Ezillo',
                ],
            ],
            [
                'code' => 'ED',
                'name' => 'Edo',
                'lgas' => [
                    'Akoko Edo',
                    'Egor',
                    'Esan-Central',
                    'Esan-North-East',
                    'Esan-South-East',
                    'Esan-West',
                    'Etsako-Central',
                    'Etsako-East',
                    'Etsako-West',
                    'Igueben',
                    'Ikpoba-Okha',
                    'Oredo',
                    'Orhionmwon',
                    'Ovia-North-East',
                    'Ovia-South-West',
                    'Owan East',
                    'Owan-West',
                    'Uhunmwonde',
                ],
                'cities' => [
                    'Benin City',
                    'Uselu',
                    'Idogbo',
                    'Irrua',
                    'Uromi',
                    'Ekpoma',
                    'Auchi',
                    'Igarra',
                    'Agenebode',
                    'Igueben',
                    'Sabongida-Ora',
                    'Fugar',
                    'Ubiaja',
                    'Afuze',
                    'Abudu',
                    'Okada',
                    'Ehor',
                    'Iguobazuwa',
                ],
            ],
            [
                'code' => 'EK',
                'name' => 'Ekiti',
                'lgas' => [
                    'Ado-Ekiti',
                    'Efon',
                    'Ekiti-East',
                    'Ekiti-South-West',
                    'Ekiti-West',
                    'Emure',
                    'Gbonyin',
                    'Ido-Osi',
                    'Ijero',
                    'Ikere',
                    'Ikole',
                    'Ilejemeje',
                    'Irepodun Ifelodun',
                    'Ise-Orun',
                    'Moba',
                    'Oye',
                ],
                'cities' => [
                    'Ado-Ekiti',
                    'Otun-Ekiti',
                    'Ikere-Ekiti',
                    'Aramoko-Ekiti',
                    'Ijero-Ekiti',
                    'Omuo-Ekiti',
                    'Ido-Ekiti',
                    'Ilawe-Ekiti',
                    'Efon-Alaaye',
                    'Iye-Ekiti',
                    'Ode-Ekiti',
                    'Igede-Ekiti',
                    'Ise-Ekiti',
                    'Emure-Ekiti',
                    'Oye-Ekiti',
                    'Ikole-Ekiti',
                ],
            ],
            [
                'code' => 'EN',
                'name' => 'Enugu',
                'lgas' => [
                    'Aninri',
                    'Awgu',
                    'Enugu-East',
                    'Enugu-North',
                    'Enugu-South',
                    'Ezeagu',
                    'Igbo-Etiti',
                    'Igbo-Eze-North',
                    'Igbo-Eze-South',
                    'Isi-Uzo',
                    'Nkanu-East',
                    'Nkanu-West',
                    'Nsukka',
                    'Oji-River',
                    'Udenu',
                    'Udi',
                    'Uzo-Uwani',
                ],
                'cities' => [
                    'Enugu',
                    'Nsukka',
                    'Nkwo Nike',
                    'Ibagwa-Aka',
                    'Enugu-Ezike',
                    'Obollo-Afor',
                    'Ogbede',
                    'Agbani',
                    'Ndeaboh',
                    'Awgu',
                    'Udi',
                    'Aguobu-Owa',
                    'Oji River',
                    'Umulona',
                    'Amagunze',
                    'Ikem',
                ],
            ],
            [
                'code' => 'GO',
                'name' => 'Gombe',
                'lgas' => [
                    'Akko',
                    'Balanga',
                    'Billiri',
                    'Dukku',
                    'Funakaye',
                    'Gombe',
                    'Kaltungo',
                    'Kwami',
                    'Nafada',
                    'Shongom',
                    'Yamaltu Deba',
                ],
                'cities' => [
                    'Gombe',
                    'Kumo',
                    'Billiri',
                    'Kaltungo',
                    'Boh',
                    'Bajoga',
                    'Deba',
                    'Mallam Sidi',
                    'Talasse',
                    'Nafada',
                    'Dukku',
                ],
            ],
            [
                'code' => 'IM',
                'name' => 'Imo',
                'lgas' => [
                    'Aboh-Mbaise',
                    'Ahiazu-Mbaise',
                    'Ehime-Mbano',
                    'Ezinihitte',
                    'Ideato-North',
                    'Ideato-South',
                    'Ihitte Uboma',
                    'Ikeduru',
                    'Isiala-Mbano',
                    'Isu',
                    'Mbaitoli',
                    'Ngor-Okpala',
                    'Njaba',
                    'Nkwerre',
                    'Nwangele',
                    'Obowo',
                    'Oguta',
                    'Ohaji-Egbema',
                    'Okigwe',
                    'Onuimo',
                    'Orlu',
                    'Orsu',
                    'Oru-East',
                    'Oru-West',
                    'Owerri-Municipal',
                    'Owerri-North',
                    'Owerri-West',
                ],
                'cities' => [
                    'Owerri',
                    'Orlu',
                    'Umundugba',
                    'Amaigbo',
                    'Dikenafai',
                    'Nnenasa',
                    'Itu',
                    'Afor-Oru',
                    'Isinweke',
                    'Mgbidi',
                    'Umumma',
                    'Nwaorieubi',
                    'Iho',
                    'Aboh',
                    'Okwe',
                    'Nkwerre',
                    'Umuelemai',
                    'Awo-Idemili',
                    'Urualla',
                    'Okigwe',
                    'Umuguma',
                    'Oguta',
                    'Umuneke-Ngor',
                    'Egbema',
                ],
            ],
            [
                'code' => 'JI',
                'name' => 'Jigawa',
                'lgas' => [
                    'Auyo',
                    'Babura',
                    'Biriniwa',
                    'Birnin-Kudu',
                    'Buji',
                    'Dutse',
                    'Gagarawa',
                    'Garki',
                    'Gumel',
                    'Guri',
                    'Gwaram',
                    'Gwiwa',
                    'Hadejia',
                    'Jahun',
                    'Kafin-Hausa',
                    'Kaugama',
                    'Kazaure',
                    'Kiri kasama',
                    'Maigatari',
                    'Malam Madori',
                    'Miga',
                    'Ringim',
                    'Roni',
                    'Sule-Tankarkar',
                    'Taura',
                    'Yankwashi',
                ],
                'cities' => [
                    'Dutse',
                    'Hadejia',
                    'Gumel',
                    'Kazaure',
                    'Auyo',
                    'Kafin Hausa',
                    'Kiri Kasamma',
                    'Roni',
                    'Gwiwa',
                    'Ringim',
                    'Birnin Kudu',
                    'Karkarna',
                    'Malam Madori',
                    'Miga',
                    'Taura',
                    'Jahun',
                    'Gantsa',
                    'Maigatari',
                    'Kiyawa',
                    'Kaugama',
                    'Gwaram',
                    'Gagarawa',
                    'Guri',
                    'Garki',
                    'Babura',
                    'Sule Tankarkar',
                    'Birniwa',
                ],
            ],
            [
                'code' => 'KD',
                'name' => 'Kaduna',
                'lgas' => [
                    'Birnin-Gwari',
                    'Chikun',
                    'Giwa',
                    'Igabi',
                    'Ikara',
                    'Jaba',
                    "Jema'A",
                    'Kachia',
                    'Kaduna-North',
                    'Kaduna-South',
                    'Kagarko',
                    'Kajuru',
                    'Kaura',
                    'Kauru',
                    'Kubau',
                    'Kudan',
                    'Lere',
                    'Makarfi',
                    'Sabon-Gari',
                    'Sanga',
                    'Soba',
                    'Zangon-Kataf',
                    'Zaria',
                ],
                'cities' => [
                    'Kaduna',
                    'Zaria',
                    'Makera',
                    'Sabon Gari',
                    'Kwoi',
                    'Hunkuyi',
                    'Makarfi',
                    'Kaura',
                    'Ikara',
                    'Giwa',
                    'Saminaka',
                    'Maigana',
                    'Turunku',
                    'Zonkwa',
                    'Kafanchan',
                    'Anchau',
                    'Gwantu',
                    'Kagarko',
                    'Kauru',
                    'Kujama',
                    'Kachia',
                    'Kajuru',
                    'Birnin Gwari',
                ],
            ],
            [
                'code' => 'KN',
                'name' => 'Kano',
                'lgas' => [
                    'Ajingi',
                    'Albasu',
                    'Bagwai',
                    'Bebeji',
                    'Bichi',
                    'Bunkure',
                    'Dala',
                    'Dambatta',
                    'Dawakin-Kudu',
                    'Dawakin-Tofa',
                    'Doguwa',
                    'Fagge',
                    'Gabasawa',
                    'Garko',
                    'Garun-Mallam',
                    'Gaya',
                    'Gezawa',
                    'Gwale',
                    'Gwarzo',
                    'Kabo',
                    'Kano-Municipal',
                    'Karaye',
                    'Kibiya',
                    'Kiru',
                    'Kumbotso',
                    'Kunchi',
                    'Kura',
                    'Madobi',
                    'Makoda',
                    'Minjibir',
                    'Nasarawa',
                    'Rano',
                    'Rimin-Gado',
                    'Rogo',
                    'Shanono',
                    'Sumaila',
                    'Takai',
                    'Tarauni',
                    'Tofa',
                    'Tsanyawa',
                    'Tudun-Wada',
                    'Ungogo',
                    'Warawa',
                    'Wudil',
                ],
                'cities' => [
                    'Kano',
                    'Ungogo',
                    'Kumbotso',
                    'Gezawa',
                    'Dawakin Kudu',
                    'Kura',
                    'Wudil',
                    'Koguna',
                    'Dawakin Tofa',
                    'Minjibir',
                    'Madobi',
                    'Garun Malam',
                    'Gwarzo',
                    'Kabo',
                    'Rimin Gado',
                    'Tofa',
                    'Bichi',
                    'Bagwai',
                    'Albasu',
                    'Tsanyawa',
                    'Warawa',
                    'Karaye',
                    'Rano',
                    'Bunkure',
                    'Kibiya',
                    'Garko',
                    'Takai',
                    'Kiru',
                    'Zakirai',
                    'Sumaila',
                    'Shanono',
                    'Rogo',
                    'Dambatta',
                    'Bebeji',
                    'Ajingi',
                    'Gaya',
                    'Tudun Wada',
                    'Kunchi',
                    'Ririwai',
                ],
            ],
            [
                'code' => 'KT',
                'name' => 'Katsina',
                'lgas' => [
                    'Bakori',
                    'Batagarawa',
                    'Batsari',
                    'Baure',
                    'Bindawa',
                    'Charanchi',
                    'Dan-Musa',
                    'Dandume',
                    'Danja',
                    'Daura',
                    'Dutsi',
                    'Dutsin-Ma',
                    'Faskari',
                    'Funtua',
                    'Ingawa',
                    'Jibia',
                    'Kafur',
                    'Kaita',
                    'Kankara',
                    'Kankia',
                    'Katsina',
                    'Kurfi',
                    'Kusada',
                    'Mai-Adua',
                    'Malumfashi',
                    'Mani',
                    'Mashi',
                    'Matazu',
                    'Musawa',
                    'Rimi',
                    'Sabuwa',
                    'Safana',
                    'Sandamu',
                    'Zango',
                ],
                'cities' => [
                    'Katsina',
                    'Mai’Adua',
                    'Funtua',
                    'Zango',
                    'Daura',
                    'Sandamu',
                    'Batagarawa',
                    'Dutsi',
                    'Bindawa',
                    'Dandume',
                    'Rimi',
                    'Dutsin-Ma',
                    'Charanchi',
                    'Malumfashi',
                    'Baure',
                    'Danja',
                    'Kusada',
                    'Mani',
                    'Bakori',
                    'Ingawa',
                    'Matazu',
                    'Sabuwa',
                    'Kurfi',
                    'Kafur',
                    'Musawa',
                    'Batsari',
                    'Mashi',
                    'Kaita',
                    'Kankia',
                    'Kankara',
                    'Jibia',
                    'Dan Musa',
                    'Safana',
                    'Faskari',
                ],
            ],
            [
                'code' => 'KE',
                'name' => 'Kebbi',
                'lgas' => [
                    'Aleiro',
                    'Arewa-Dandi',
                    'Argungu',
                    'Augie',
                    'Bagudo',
                    'Birnin-Kebbi',
                    'Bunza',
                    'Dandi',
                    'Fakai',
                    'Gwandu',
                    'Jega',
                    'Kalgo',
                    'Koko-Besse',
                    'Maiyama',
                    'Ngaski',
                    'Sakaba',
                    'Shanga',
                    'Suru',
                    'Wasagu/Danko',
                    'Yauri',
                    'Zuru',
                ],
                'cities' => [
                    'Birnin Kebbi',
                    'Zuru',
                    'Kalgo',
                    'Jega',
                    'Aliero',
                    'Gwandu',
                    'Argungu',
                    'Bunza',
                    'Besse',
                    'Maiyama',
                    'Dakingari',
                    'Shanga',
                    'Ribah',
                    'Augie',
                    'Sakaba',
                    'Kamba',
                    'Wara',
                    'Mahuta',
                    'Bagudo',
                    'Kangiwa',
                    'Yelwa',
                ],
            ],
            [
                'code' => 'KO',
                'name' => 'Kogi',
                'lgas' => [
                    'Adavi',
                    'Ajaokuta',
                    'Ankpa',
                    'Dekina',
                    'Ibaji',
                    'Idah',
                    'Igalamela-Odolu',
                    'Ijumu',
                    'Kabba Bunu',
                    'Kogi',
                    'Lokoja',
                    'Mopa-Muro',
                    'Ofu',
                    'Ogori Magongo',
                    'Okehi',
                    'Okene',
                    'Olamaboro',
                    'Omala',
                    'Oyi',
                    'Yagba-East',
                    'Yagba-West',
                ],
                'cities' => [
                    'Idah',
                    'Lokoja',
                    'Akpafa',
                    'Obangede',
                    'Ogaminana',
                    'Okene',
                    'Ankpa',
                    'Okpo',
                    'Iyara',
                    'Odo-Ere',
                    'Ugwolawo',
                    'Onyedega',
                    'Isanlu',
                    'Adogo',
                    'Koton-Karfe',
                    'Ajaka',
                    'Dekina',
                    'Oguma',
                    'Abejukolo',
                    'Kabba',
                    'Mopa',
                ],
            ],
            [
                'code' => 'KW',
                'name' => 'Kwara',
                'lgas' => [
                    'Asa',
                    'Baruten',
                    'Edu',
                    'Ekiti (Araromi/Opin)',
                    'Ilorin-East',
                    'Ilorin-South',
                    'Ilorin-West',
                    'Isin',
                    'Kaiama',
                    'Moro',
                    'Offa',
                    'Oke-Ero',
                    'Oyun',
                    'Pategi',
                ],
                'cities' => [
                    'Ilorin',
                    'Offa',
                    'Fufu',
                    'Ilemona',
                    'Iloffa',
                    'Omu-Aran',
                    'Araromi-Opin',
                    'Owu-Isin',
                    'Lafiagi',
                    'Afon',
                    'Share',
                    'Patigi',
                    'Oke-Oyi',
                    'Bode Saadu',
                    'Kosubosu',
                    'Kaiama',
                ],
            ],
            [
                'code' => 'LA',
                'name' => 'Lagos',
                'lgas' => [
                    'Agege',
                    'Ajeromi-Ifelodun',
                    'Alimosho',
                    'Amuwo-Odofin',
                    'Apapa',
                    'Badagry',
                    'Epe',
                    'Eti-Osa',
                    'Ibeju-Lekki',
                    'Ifako-Ijaiye',
                    'Ikeja',
                    'Ikorodu',
                    'Kosofe',
                    'Lagos-Island',
                    'Lagos-Mainland',
                    'Mushin',
                    'Ojo',
                    'Oshodi-Isolo',
                    'Shomolu',
                    'Surulere',
                    'Yewa-South',
                ],
                'cities' => [
                    'Isolo',
                    'Isheri-Oshun',
                    'Ikotun',
                    'Isheri-Olofin',
                    'Meiran',
                    'Ejigbo',
                    'Ketu',
                    'Shangisha',
                    'Oworonshoki',
                    'ushin',
                    'Abesan',
                    'Magodo',
                    'Egbe',
                    'Igando',
                    'Idimu',
                    'Ayobo',
                    'Iju',
                    'Ifako',
                    'Abule Egba',
                    'Agboyi',
                    'Ikosi',
                    'Okota',
                    'Somolu',
                    'Ipaja',
                    'Oregun',
                    'Isheri-Oke',
                    'Oshodi',
                    'Oke-Afa',
                    'Ojodu',
                    'Ogudu',
                    'Bariga',
                    'Ilupeju',
                    'Obanikoro',
                    'Akowonjo',
                    'Agege',
                    'Ijegun',
                    'Alagbado',
                    'Aboru',
                    'Olota',
                    'Ojokoro',
                    'Ikola',
                    'Ajasa',
                    'Baruwa',
                    'Ewu',
                    'Abule-Onigbagbo',
                    'Odi-Olowo',
                    'Shasha',
                    'Mende',
                    'Ipodo',
                    'Alimosho',
                    'Badagry',
                    'Ajara',
                    'Iworo',
                    'Ajido',
                    'Akarakunmo',
                    'Gbaji',
                    'Aseri',
                    'Egan',
                    'Agonrin',
                    'Ahanve',
                    'Mowo',
                    'Itoga',
                    'Shibiri',
                    'Ekunpa',
                    'Aradagun',
                    'Kankon',
                    'Mosafejo',
                    'Gayingbo-Topa',
                    'Apa',
                    'Ropoji',
                    'Oranyan',
                    'Tafi-Awori',
                    'Yeketome',
                    'Pota',
                    'Seme',
                    'Iyagbe',
                    'Ajegunle',
                    'Aiyetoro',
                    'Festac Town and Satellite Towns',
                    'Iba',
                    'Kirikiri',
                    'Agboju-Amuwo',
                    'Okokomaiko',
                    'Ojo',
                    'Amukoko',
                    'Alaba-Oro',
                    'Ijofin',
                    'Igbanko',
                    'Imore',
                    'Ibeshe',
                    'Ijanikin',
                    'Ilogbo Eremi',
                    'Ilado',
                    'Abule-Ado',
                    'Odan [Soba, Onireke,etc]',
                    'Ikorodu',
                    'Egbin',
                    'Igbogbo',
                    'Imota',
                    'Ijede',
                    'Maya Adio',
                    'Odogunyan',
                    'Isiu',
                    'Igbokuta',
                    'Ewu-Elepe',
                    'Baiyeku',
                    'Oreta',
                    'Ofin',
                    'Gberigbe',
                    'Erikorodo',
                    'Igbalu',
                    'Tarkwa Bay',
                    'Victoria Island',
                    'Iru',
                    'Lagos Island',
                    'Ikoyi',
                    'Obalende',
                    'Oto',
                    'Ijora',
                    'Apapa',
                    'Ebute-Meta',
                    'Yaba',
                    'Ido',
                    'Sangotedo',
                    'Mayegun',
                    'Ogombo',
                    'Ogoyo',
                    'Okun-Ibeju',
                    'Moba',
                    'Alaguntan',
                    'Ado',
                    'Langbasa',
                    'Ilasan',
                    'Igbo-Efon',
                    'Ikota',
                    'Itire',
                    'Coker-Aguda',
                    'Ikate-Elegushi',
                    'Ajiran',
                    'Tomaro',
                    'Abagbo',
                    'Igbo-Ejo',
                    'Epe',
                    'Orugbo-Iddo',
                    'Agbowa-Ikosi',
                    'Ilara',
                    'Odo-Ayandelu',
                    'Odoragunsin',
                    'Igbooye',
                    'Naforija',
                    'Igbodu',
                    'Ejinrin',
                    'Poka',
                    'Itoikin',
                    'Idotun',
                    'Ita-Oko',
                    'Omi',
                    'Temu',
                    'Ise',
                    'Debojo',
                    'Apawa',
                    'Aba-Titun',
                    'Abomiti',
                    'Afere',
                    'Apakin',
                    'Abalaye',
                    'Origanrigan',
                    'Kayetoro Eleko',
                    'Yeunda',
                    'Okunraye',
                    'Keta',
                    'Arapagi',
                    'Aiyeteju',
                    'Okun-Folu',
                    'Osoroko',
                    'Olomowewe',
                    'Ibeju',
                    'Lekki',
                    'Akodo',
                    'Otolu',
                    'Magbon-Alade',
                    'Oriba',
                    'Iwerekun',
                    'Iberekodo',
                    'Idado',
                    'Okun Igando-Orudu',
                    'Tiye',
                    'Awoyaya',
                    'Ote-Omi',
                    'Bogije',
                    'Siriwon',
                    'Idaso',
                    'Orimedu',
                    'Olorunkoya',
                    'Ojota',
                    'Ode-Ifa',
                    'Igbesibi',
                    'Igbolomi',
                ],
            ],
            [
                'code' => 'NA',
                'name' => 'Nassarawa',
                'lgas' => [
                    'Akwanga',
                    'Awe',
                    'Doma',
                    'Karu',
                    'Keana',
                    'Keffi',
                    'Kokona',
                    'Lafia',
                    'Nasarawa',
                    'Nasarawa-Eggon',
                    'Obi',
                    'Wamba',
                    'Toto',
                ],
                'cities' => [
                    'Ado Nasarawa',
                    'Lafia',
                    'Nasarawa',
                    'Keffi',
                    'Wamba',
                    'Toto',
                    'Nasarawa-Eggon',
                    'Masaka',
                    'Akwanga',
                    'Keana',
                    'Umaish',
                    'Doma',
                    'Obi',
                    'Mararaba',
                    'Ohizi Ogabo',
                    'Loko',
                    'New Karu',
                    'Gidan Mangoro',
                    'Marmara',
                    'Kokouna',
                    'Laminga',
                    'New Nyanya',
                ],
            ],
            [
                'code' => 'NI',
                'name' => 'Niger',
                'lgas' => [
                    'Agaie',
                    'Agwara',
                    'Bida',
                    'Borgu',
                    'Bosso',
                    'Chanchaga',
                    'Edati',
                    'Gbako',
                    'Gurara',
                    'Katcha',
                    'Kontagora',
                    'Lapai',
                    'Lavun',
                    'Magama',
                    'Mariga',
                    'Mashegu',
                    'Mokwa',
                    'Moya',
                    'Paikoro',
                    'Rafi',
                    'Rijau',
                    'Shiroro',
                    'Suleja',
                    'Tafa',
                    'Wushishi',
                ],
                'cities' => [
                    'Minna',
                    'Bida',
                    'Kontagora',
                    'Suleja',
                    'Sabon Wuse',
                    'Enagi',
                    'Maikunkele',
                    'Gawu Babangida',
                    'Sarkin Pawa',
                    'Paiko',
                    'Lemu',
                    'Agaie',
                    'Katcha',
                    'Mokwa',
                    'Rijau',
                    'Kutigi',
                    'Kagara',
                    'Nasko',
                    'Kuta',
                    'Wushishi',
                    'Lapai',
                    'Agwara',
                    'Bangi',
                    'Mashegu',
                    'New Bussa',
                ],
            ],
            [
                'code' => 'OG',
                'name' => 'Ogun',
                'lgas' => [
                    'Abeokuta-North',
                    'Abeokuta-South',
                    'Ado-Odo Ota',
                    'Ewekoro',
                    'Ifo',
                    'Ijebu-East',
                    'Ijebu-North',
                    'Ijebu-North-East',
                    'Ijebu-Ode',
                    'Ikenne',
                    'Imeko-Afon',
                    'Ipokia',
                    'Obafemi-Owode',
                    'Odeda',
                    'Odogbolu',
                    'Ogun-Waterside',
                    'Remo-North',
                    'Shagamu',
                    'Yewa North',
                ],
                'cities' => [
                    'Abeokuta',
                    'Ijebu-Ode',
                    'Ifo',
                    'Ikenne',
                    'Ota',
                    'Atan',
                    'Shagamu',
                    'Isara',
                    'Ijebu-Igbo',
                    'Ipokia',
                    'Ilaro',
                    'Odogbolu',
                    'Owode',
                    'Ayetoro',
                    'Itori',
                    'Abigi',
                    'Odeda',
                    'Imeko',
                    'Ogbere',
                ],
            ],
            [
                'code' => 'ON',
                'name' => 'Ondo',
                'lgas' => [
                    'Akoko North-East',
                    'Akoko North-West',
                    'Akoko South-West',
                    'Akoko South-East',
                    'Akure-North',
                    'Akure-South',
                    'Ese-Odo',
                    'Idanre',
                    'Ifedore',
                    'Ilaje',
                    'Ile-Oluji-Okeigbo',
                    'Irele',
                    'Odigbo',
                    'Okitipupa',
                    'Ondo West',
                    'Ondo-East',
                    'Ose',
                    'Owo',
                ],
                'cities' => [
                    'Ikare',
                    'Akure',
                    'Owo',
                    'Ondo',
                    'Igbara-Oke',
                    'Oka',
                    'Ile-Oluji',
                    'Oke-Agbe',
                    'Isua',
                    'Okitipupa',
                    'Bolorunduro',
                    'Igbekebo',
                    'Igbokoda',
                    'Iju',
                    'Ita-Ogbolu',
                    'Ode-Irele',
                    'Owena',
                    'Ore',
                    'Ifon',
                ],
            ],
            [
                'code' => 'OS',
                'name' => 'Osun',
                'lgas' => [
                    'Atakumosa West',
                    'Atakumosa East',
                    'Ayedaade',
                    'Ayedire',
                    'Boluwaduro',
                    'Boripe',
                    'Ede South',
                    'Ede North',
                    'Egbedore',
                    'Ejigbo',
                    'Ife North',
                    'Ife South',
                    'Ife-Central',
                    'Ife-East',
                    'Ifelodun',
                    'Ila',
                    'Ilesa-East',
                    'Ilesa-West',
                    'Irepodun',
                    'Irewole',
                    'Isokan',
                    'Iwo',
                    'Obokun',
                    'Odo-Otin',
                    'Ola Oluwa',
                    'Olorunda',
                    'Oriade',
                    'Orolu',
                    'Osogbo',
                ],
                'cities' => [
                    'Ile-Ife',
                    'Osogbo',
                    'Iwo',
                    'Ilobu',
                    'Ilesa',
                    'Ifon',
                    'Iragbiji',
                    'Ikirun',
                    'Ile-Ogbo',
                    'Okuku',
                    'Otan Ayegbaju',
                    'Apomu',
                    'Ikire',
                    'Ejigbo',
                    'Oke-Ila',
                    'Ijebu-Jesa',
                    'Ede',
                    'Awo',
                    'Ibokun',
                    'Bode Osi',
                    'Ifetedo',
                    'Ila Orangun',
                    'Ipetumodu',
                    'Gbongan',
                    'Iperindo',
                    'Osu',
                ],
            ],
            [
                'code' => 'OY',
                'name' => 'Oyo',
                'lgas' => [
                    'Afijio',
                    'Akinyele',
                    'Atiba',
                    'Atisbo',
                    'Egbeda',
                    'Ibadan North',
                    'Ibadan North-East',
                    'Ibadan North-West',
                    'Ibadan South-East',
                    'Ibadan South-West',
                    'Ibarapa-Central',
                    'Ibarapa-East',
                    'Ibarapa-North',
                    'Ido',
                    'Ifedayo',
                    'Irepo',
                    'Iseyin',
                    'Itesiwaju',
                    'Iwajowa',
                    'Kajola',
                    'Lagelu',
                    'Ogo-Oluwa',
                    'Ogbomosho-North',
                    'Ogbomosho-South',
                    'Olorunsogo',
                    'Oluyole',
                    'Ona-Ara',
                    'Orelope',
                    'Ori-Ire',
                    'Oyo-West',
                    'Oyo-East',
                    'Saki-East',
                    'Saki-West',
                    'Surulere',
                ],
                'cities' => [
                    'Ibadan',
                    'Ogbomoso',
                    'Oyo',
                    'Iseyin',
                    'Egbeda',
                    'Akanran',
                    'Iyana-Ofa',
                    'Moniya',
                    'Okeho',
                    'Idi-Ayunre',
                    'Igbo-Ora',
                    'Jobele',
                    'Iresa-Adu',
                    'Eruwa',
                    'Ajaawa',
                    'Kisi',
                    'Igboho',
                    'Ido',
                    'Otu',
                    'Ayete',
                    'Igbeti',
                    'Ikoyi-Ile',
                    'Ago-Amodu',
                    'Saki',
                    'Iwere-Ile',
                    'Tede',
                ],
            ],
            [
                'code' => 'PL',
                'name' => 'Plateau',
                'lgas' => [
                    'Barkin-Ladi',
                    'Bassa',
                    'Bokkos',
                    'Jos-East',
                    'Jos-North',
                    'Jos-South',
                    'Kanam',
                    'Kanke',
                    'Langtang-North',
                    'Langtang-South',
                    'Mangu',
                    'Mikang',
                    'Pankshin',
                    "Qua'an Pan",
                    'Riyom',
                    'Shendam',
                    'Wase',
                ],
                'cities' => [
                    'Jos',
                    'Bukuru',
                    'Riyom',
                    'Barkin Ladi',
                    'Langtang',
                    'Mangu',
                    'Tunkus',
                    'Bassa',
                    'Bokkos',
                    'Angware',
                    'Pankshin',
                    'Kwal',
                    'Baap',
                    'Shendam',
                    'Mabudi',
                    'Dengi',
                    'Wase',
                ],
            ],
            [
                'code' => 'RI',
                'name' => 'Rivers',
                'lgas' => [
                    'Abua Odual',
                    'Ahoada-East',
                    'Ahoada-West',
                    'Akuku Toru',
                    'Andoni',
                    'Asari-Toru',
                    'Bonny',
                    'Degema',
                    'Eleme',
                    'Emuoha',
                    'Etche',
                    'Gokana',
                    'Ikwerre',
                    'Khana',
                    'Obio Akpor',
                    'Ogba-Egbema-Ndoni',
                    'Ogba Egbema Ndoni',
                    'Ogu Bolo',
                    'Okrika',
                    'Omuma',
                    'Opobo Nkoro',
                    'Oyigbo',
                    'Port-Harcourt',
                    'Tai',
                ],
                'cities' => [
                    'Port Harcourt',
                    'Okrika',
                    'Kpor',
                    'Buguma',
                    'Rumuodomaya',
                    'Ogu',
                    'Nchia',
                    'Saakpenwa',
                    'Ngo',
                    'Opobo',
                    'Akinima',
                    'Bori',
                    'Ahoada',
                    'Abua',
                    'Bonny',
                    'Omoku',
                    'Afam',
                    'Okehi',
                    'Eberi',
                    'Abonnema',
                    'Degema',
                    'Isiokpo',
                    'Emuoha',
                ],
            ],
            [
                'code' => 'SO',
                'name' => 'Sokoto',
                'lgas' => [
                    'Binji',
                    'Bodinga',
                    'Dange-Shuni',
                    'Gada',
                    'Goronyo',
                    'Gudu',
                    'Gwadabawa',
                    'Illela',
                    'Kebbe',
                    'Kware',
                    'Rabah',
                    'Sabon Birni',
                    'Shagari',
                    'Silame',
                    'Sokoto-North',
                    'Sokoto-South',
                    'Tambuwal',
                    'Tangaza',
                    'Tureta',
                    'Wamako',
                    'Wurno',
                    'Yabo',
                ],
                'cities' => [
                    'Sokoto',
                    'Bodinga',
                    'Wamako',
                    'Wurno',
                    'Gwadabawa',
                    'Illela',
                    'Binji',
                    'Kware',
                    'Tambuwal',
                    'Silame',
                    'Dange',
                    'Yabo',
                    'Shagari',
                    'Gada',
                    'Goronyo',
                    'Kebbe',
                    'Sabon Birni',
                    'Isa',
                    'Rabah',
                    'Tureta',
                    'Gidan Madi',
                    'Balle',
                ],
            ],
            [
                'code' => 'TA',
                'name' => 'Taraba',
                'lgas' => [
                    'Ardo-Kola',
                    'Bali',
                    'Donga',
                    'Gashaka',
                    'Gassol',
                    'Ibi',
                    'Jalingo',
                    'Karim-Lamido',
                    'Kurmi',
                    'Lau',
                    'Sardauna',
                    'Takum',
                    'Ussa',
                    'Wukari',
                    'Yorro',
                    'Zing',
                ],
                'cities' => [
                    'Jalingo',
                    'Wukari',
                    'Zing',
                    'Pantisawa',
                    'Takum',
                    'Gembu',
                    'Mutum Biyu',
                    'Donga',
                    'Lissam',
                    'Sunkani',
                    'Ibi',
                    'Lau',
                    'Karim Lamido',
                    'Bali',
                    'Baissa',
                    'Serti',
                ],
            ],
            [
                'code' => 'YO',
                'name' => 'Yobe',
                'lgas' => [
                    'Bade',
                    'Bursari',
                    'Damaturu',
                    'Fika',
                    'Fune',
                    'Geidam',
                    'Gujba',
                    'Gulani',
                    'Jakusko',
                    'Karasuwa',
                    'Machina',
                    'Nangere',
                    'Nguru',
                    'Potiskum',
                    'Tarmuwa',
                    'Yunusari',
                    'Yusufari',
                ],
                'cities' => [
                    'Damaturu',
                    'Gashua',
                    'Nguru',
                    'Potiskum',
                    'Jajimaji',
                    'Sabon Garin Nangere',
                    'Fika',
                    'Damagum',
                    'Jakusko',
                    'Machina',
                    'Bara',
                    'Buni Yadi',
                    'Geidam',
                    'Dapchi',
                    'Yusufari',
                    'Kanamma',
                    'Babban Gida',
                ],
            ],
            [
                'code' => 'ZA',
                'name' => 'Zamfara',
                'lgas' => [
                    'Anka',
                    'Bakura',
                    'Birnin Magaji/Kiyaw',
                    'Bukkuyum',
                    'Bungudu',
                    'Gummi',
                    'Gusau',
                    'Isa',
                    'Kaura-Namoda',
                    'Kiyawa',
                    'Maradun',
                    'Maru',
                    'Shinkafi',
                    'Talata-Mafara',
                    'Tsafe',
                    'Zurmi',
                ],
                'cities' => [
                    'Gusau',
                    'Kaura Namoda',
                    'Birnin Magaji',
                    'Shinkafi',
                    'Bungudu',
                    'Tsafe',
                    'Zurmi',
                    'Maradun',
                    'Talata Mafara',
                    'Bakura',
                    'Bukkuyum',
                    'Gummi',
                    'Anka',
                    'Maru',
                ],
            ],
        ];

        $nigeria = Country::firstWhere('nicename', 'Nigeria');
        if (!is_null($nigeria)) {
            foreach ($states as $stateData) {
                $state = State::create([
                    'country_id' => $nigeria->id,
                    'name' => $stateData['name'],
                ]);

                if(! is_null($state) && array_key_exists('cities', $stateData))
                {
                    foreach($stateData['cities'] as $cityData)
                    {
                        Town::create([
                            'name' => $cityData,
                            'state_id' => $state->id
                        ]);
                    }
                }
            }
        }
    }
}
